spring:
  profiles:
    active: dev

---
server:
  port: 8004
#spring的配置
spring:
  profiles: dev
  application:
    name: config-dev

---
server:
  port: 8005
spring:
  profiles: test
  application:
    name: config-test
  
